{
 "title": "Tools Comparison",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "description": "Networkl Traffic by Telegraf, Prometheus and Grafana",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(process_network_receive_bytes_total{job=\"job-name\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(process_network_receive_bytes_total{job=\"prometheus\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(process_network_receive_bytes_total{job=\"grafana\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "description": "Memory usage by Grafana , Telegraf and Prometheus",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"telegraf\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_virtual_memory_bytes{job=\"prometheus\"}\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "\nprocess_virtual_memory_bytes{job=\"grafana\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "Cpu usage comparison of grafanaG Telegraf and Prometheus",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"job-name\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(process_cpu_seconds_total{job=\"prometheus\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(process_cpu_seconds_total{job=\"grafana\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query Execution Duration",
   "type": "timeseries",
   "description": "Time taken by prometheus to execute queries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "engine_query_duration_seconds{job=\"job-name\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafana Average Request Duration",
   "type": "gauge",
   "description": "Average request duration of grafana",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafana_api_dataproxy_request_all_milliseconds{job=\"grafana\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}