{
 "title": "Book Nest Backend Monitoring Telegraf Metrics Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Heap Memory Usage",
   "type": "timeseries",
   "description": "Tracks the number of bytes currently allocated in the heap",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "go_memstats_heap_alloc_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": " Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active Goroutines",
   "type": "stat",
   "description": "Current number of active goroutines",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Next GC Trigger (Bytes)",
   "type": "gauge",
   "description": "Heap size (in bytes) at which the next garbage collection will trigge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "go_memstats_next_gc_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GC Cycles Count",
   "type": "timeseries",
   "description": "Total number of garbage collection cycles since application started",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 6 },
   "targets": [
    { "expr": "go_gc_duration_seconds_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": " Active Threads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "go_threads", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Usage Over Time",
   "type": "timeseries",
   "description": "Displays the CPU usage of the Node.js process",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Garbage Collection Duration",
   "type": "timeseries",
   "description": "Visualize the duration of garbage collection cycles in seconds across different quantiles (e.g., 50th, 75th percentile). Helps monitor the impact of garbage collection on application performance.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    { "expr": "go_gc_duration_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Heap Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 15 },
   "targets": [
    { "expr": "go_memstats_heap_alloc_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Network Traffic Received",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 15 },
   "targets": [
    {
     "expr": "process_network_receive_bytes_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Routes Req Duration",
   "type": "piechart",
   "description": "Response times of API endpoints",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "gauge",
   "description": "Displays the current number of open file descriptors by the Node.js process",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_open_fds\n", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "targets": [
    { "expr": "nodejs_eventloop_lag_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Node Process Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_start_time_seconds", "legendFormat": "__auto" }
   ]
  }
 ]
}