global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "auth"
    static_configs:
      - targets: ["auth:5000"]
  - job_name: "books"
    static_configs:
      - targets: ["books:5001"]
  - job_name: "borrow"
    static_configs:
      - targets: ["borrow:5002"]
  - job_name: "telegraf"
    static_configs:
      - targets: ["telegraf:9273"]
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:3000"]
